apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
          - name: CONFIGMAPVAR
            valueFrom:
              configMapKeyRef:
                name: my-ports-config
                key: nginx-port
      - name: multitool
        image: praqma/network-multitool:latest
        env:
          - name: CONFIGMAPVAR
            valueFrom:
              configMapKeyRef:
                name: my-ports-config
                key: multitool-port
        command:
          - sleep
          - "3600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-ports-config
  namespace: default
data:
  nginx-port: "80"
  multitool-port: "8080"
  nginx.conf: |
    server {
        listen $(nginx-port);
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }