apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.test
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front
            port:
              number: 80
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: back
            port:
              number: 80