apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: nginx-port
      port: 80
      targetPort: 9001
    - name: multitool-port
      port: 8080
      targetPort: 9002