apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:latest
    command:
      - sleep
      - "3600"
  restartPolicy: Never